In [1]:
import numpy as np

In [2]:
before = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
after = before.reshape((5, 2))
after


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### VSTACK - np.vstack([a1, a2, ...])

In [3]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])  # stack v1 on top of v2
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
np.hstack([v1, v2])  # stack v2 to the right of v1

array([1, 2, 3, 4, 5, 6, 7, 8])