In [2]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [4]:
# GET SPECIFIC ELEMENT [r, c]
print(a[1, 5], a[1, -2])

13 13


In [6]:
# GET SPECIFIC ROW
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [7]:
# GET SPECIFIC COLUMN
a[:, 3]

array([ 4, 11])

In [8]:
# USING STEPS
a[0, 1:6:2]


array([2, 4, 6])

In [11]:
a[1, 5] = 20  # MODIFY ELEMENT
a[:, 2] = [1, 2]  # MODIFY COLUMN
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [16]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b, b.shape, sep="\n\n")


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

(2, 2, 2)


In [18]:
b[0, 1, 1]  # GET SPECIFIC ELEMENT (work outside in)

4

In [19]:
# REPLACE
b[:, 1, :] = [[9, 9], [8, 8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

In [20]:
b[:, 1, 1] = [1000, 19892]
b

array([[[    1,     2],
        [    9,  1000]],

       [[    5,     6],
        [    8, 19892]]])

#### USING LISTS ACCESS SPECIFIC

In [6]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[2, 5, 8]]

array([3, 6, 9])

In [3]:
filedata = np.genfromtxt("data.txt", delimiter=",", dtype="int32")

In [4]:
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [5]:
filedata[
    [0, 2], 1:3
]  # GET SPECIFIC ELEMENTS i.e of first and third row get second and third column

array([[13, 21],
       [22, 33]])