In [1]:
import numpy as np

In [7]:
filedata = np.genfromtxt("data.txt", delimiter=",", dtype="int32")
print(filedata)


[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [4]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [5]:
filt = filedata > 50
filedata[filt]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [6]:
np.any(filedata > 50, axis=0) # returns True if any element in the column is greater than 50

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [8]:
filt = (filedata > 50) & (filedata < 100)
filedata[filt]


array([75, 75, 55, 78, 76, 88])

In [9]:
filt = ~(filedata > 50) & (filedata < 100)
filedata[filt]


array([ 1, 13, 21, 11,  4,  3, 34,  6,  7,  8,  0,  1,  2,  3,  4,  5,  3,
       42, 12, 33,  4,  6,  4,  3,  4,  5,  6,  7,  0, 11, 12,  1, 22, 33,
       11, 11,  2,  1,  0,  1,  2,  9,  8,  7,  1])