In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a + 2  # add 2 to each element
a - 2  # subtract 2 from each element
a * 2  # multiply each element by 2
a / 2  # divide each element by 2
a**2  # square each element

array([3, 4, 5])

In [3]:
b = np.array([1, 0, 1])
a + b  # add elements of a and b


array([2, 2, 4])

In [4]:
# TAKE THE SIN OF ALL ELEMENTS
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [5]:
# TAKE THE COS OF ALL ELEMENTS
np.cos(a)


array([ 0.54030231, -0.41614684, -0.9899925 ])

#### Linear Algebra

matmul(a,b )

In [6]:
a = np.full((2, 3), 1)  # create a 2x3 array of all ones
b = np.full((3, 2), 2)  # create a 3x2 array of all twos
np.matmul(a, b)  # matrix multiplication


array([[6, 6],
       [6, 6]])

In [7]:
c = np.identity(3)  # create a 3x3 identity matrix
np.linalg.det(c)  # determinant of c


1.0