In [1]:
# numpy is a library for numerical computations in python
# it also provides a high-performance multidimensional array object, and tools for working with these arrays
# list vs nparray -
# 1. list can contain different types of data, nparray can only contain one type of data
# 2. list is slower than nparray
# 3. list is less memory efficient than nparray
import numpy as np


In [2]:
a = np.array([1, 2, 3])  # 1D array
a


array([1, 2, 3])

In [8]:
b = np.array([[1.0, 2, 3], [4, 5, 6]])  # 2D array
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
# GET DIMENSION
print(a.ndim)
print(b.ndim)


1
2


In [6]:
# GET SHAPE
print(a.shape, b.shape)

(3,) (2, 3)


In [12]:
# GET TOTAL SIZE
print(a.size, b.size)

3 6


## Data Type


In [9]:
# GET TYPE
print(a.dtype, b.dtype)


int32 float64


In [11]:
a = np.array([1, 2, 3], dtype="float32")
print(a, a.dtype)

[1. 2. 3.] float32
