In [2]:
import numpy as np

In [3]:
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [6]:
np.ones((4, 4, 2), dtype="int32")

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [7]:
# any number - syn
# np.full((shape), number)

np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [8]:
# full_like
a = np.array([[1, 2, 3], [4, 5, 6]])
np.full_like(a, 4)


array([[4, 4, 4],
       [4, 4, 4]])

In [13]:
# random decimal numbers
# syn - np.random.rand(d1, d2, d3, ...)
np.random.rand(4, 2)


array([[0.45909745, 0.75315914],
       [0.95064234, 0.68859334],
       [0.20660276, 0.86887068],
       [0.03190701, 0.15642354]])

In [14]:
# random integer values
# syn - np.random.randint(low, high, size=shape)
np.random.randint(4, 7, size=(3, 3))


array([[5, 5, 6],
       [6, 6, 5],
       [6, 5, 4]])

In [16]:
np.identity(5, dtype="int32")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
a = np.array([1, 2, 3])  # def axis = 0
np.repeat(a, 3, axis=0)
# nd array has the number of axis = 0, 1, 2, 3, ...
# axis = 0 - row
# axis = 1 - column
# axis = 2 - 3d array
# axis = 3 - 4d array
# ...

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [24]:
# repeat an array
arr = np.array([[1, 2, 3]])

# syn - np.repeat(arr, number_of_repeats, axis)
# axis - 0 for columns, 1 for rows
# if axis = 0 menans repeat each row 3 times
# if axis = 1 means repeat each column 3 times

r1 = np.repeat(arr, 3, axis=0)
r1


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
np.repeat(arr, 3, axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [6]:
a = np.ones((5, 5), dtype="int")
a[1:4, 1:4] = np.zeros((3, 3), dtype="int")
a[2, 2] = 9
a


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

# COPYING ARRAYS - BE CAREFUL, shallow , deep copy

In [8]:
# be careful with copying arrays and changing them
# if you want to copy an array, use the copy() method
# if you use the assignment operator, it will change the original array
# example
a = np.array([1, 2, 3])
b = a
b[0] = 9
print(a)


[9 2 3]


In [10]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 9
print("a = ", a)
print("b = ", b)

a =  [1 2 3]
b =  [9 2 3]
